name: Trade Engine CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: testuser       
          POSTGRES_PASSWORD: testpassword 
          POSTGRES_DB: testdb           
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build
      run: go build -v ./...

    - name: Run Integration Tests
      env:
        DB_USER: testuser      
        DB_PASSWORD: testpassword 
        DB_HOST: localhost      
        DB_PORT: 5432
        DB_NAME: testdb        
      run: go test -v ./...
